# Builds and Pushes a Docker Image to DockerHub. It will get stored in the DockerRepo SmartCity.
# It uses a Ubuntu 20.04 OS
# It uses Docker official login action
# Uses Docker Build and Push Action to build and push the Image to DockerHub.
name: Test Backend then Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check-out git repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build:
    needs: test-backend
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: merlinchiodo/smartcity:buergerbuero,merlinchiodo/smartcity:buergerbuero_1.0.0-${{ github.sha }}
