name: Super-Linter-Tests

on: push

jobs:
  super-lint:
      name: Lint the whole code base with superlinter
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the new commited code
          uses: actions/checkout@v3
        
        - name: Run Super-Linter-Tests
          uses: github/super-linter@v4
          env:
            VALIDATE_ALL_CODEBASE: true
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
